[workspace]
members = [
    "crates/meta-swap-domain",
    "crates/meta-swap-application",
    "crates/meta-swap-infrastructure",
    "crates/meta-swap-presentation",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "UNLICENSED"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
module_name_repetitions = "allow"
must_use_candidate = "allow"
