[package]
name = "meta-swap-infrastructure"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
meta-swap-application = { path = "../meta-swap-application" }
sqlx = { version = "0.8.6", default-features = false, features = ["migrate", "postgres", "runtime-tokio-rustls"] }

[dev-dependencies]
meta-swap-domain = { path = "../meta-swap-domain" }
tokio = { version = "1.44", features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
